#!/usr/bin/bash
echo "Installing node modules for Adder"
cd /home/dev/case-studies/Adder
npm i
cd client
npm i
cd ~
echo "Generating APIs for Adder"
python3.8 -m codegen protocols/Adder.scr Adder Svr node -o case-studies/Adder/src
python3.8 -m codegen protocols/Adder.scr Adder Client browser -s Svr -o case-studies/Adder/client/src
echo "SUCCESS: generated APIs for Adder"
echo "Building Adder application"
cd case-studies/Adder
npm run build
echo "SUCCESS: built Adder"
echo "To run the case study, you can do"
echo "  $ cd ~/case-studies/Adder"
echo "  $ npm start"
echo ""
echo "and visit http://localhost:8080"
echo "" 
